name: ifood_party_bot
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Igor Borges <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  teledart:
    path: /Users/igor/Projects/TeleDart
  json_annotation: ^1.0.0

dev_dependencies:
  test: ^1.0.0
  build_runner: ^0.10.0
  json_serializable: ^1.0.0
